import type { LoremBabelConfig } from '../mod.ts'

/**
 * @module
 * Config used with LoremBabel to generate nonsense placeholder text in `ko` locale.
 */

/** LoremBabel configuration for `ko` locale */
const config: LoremBabelConfig = {
	'locale': 'ko',
	'sentenceSeparator': ' ',
	'wordSeparators': [
		{ 'weight': 142, 'separator': ' ' },
		{ 'weight': 14, 'separator': ', ' },
	],
	'sentenceWrappers': [
		{ 'weight': 9, 'start': '', 'end': '.' },
		{ 'weight': 1, 'start': '', 'end': '' },
	],
	'vocabulary': [
		{ 'word': '문자', 'weight': 8 },
		{ 'word': '인코딩', 'weight': 5 },
		{ 'word': '있다', 'weight': 4 },
		{ 'word': '유니코드', 'weight': 3 },
		{ 'word': '유니코드는', 'weight': 3 },
		{ 'word': '또한', 'weight': 2 },
		{ 'word': '위한', 'weight': 2 },
		{ 'word': '유니코드의', 'weight': 2 },
		{ 'word': '조', 'weight': 2 },
		{ 'word': '국제', 'weight': 2 },
		{ 'word': '영어', 'weight': 1 },
		{ 'word': '정식', 'weight': 1 },
		{ 'word': '명칭', 'weight': 1 },
		{ 'word': '는', 'weight': 1 },
		{ 'word': '전', 'weight': 1 },
		{ 'word': '세계의', 'weight': 1 },
		{ 'word': '모든', 'weight': 1 },
		{ 'word': '문자를', 'weight': 1 },
		{ 'word': '컴퓨터에서', 'weight': 1 },
		{ 'word': '일관되게', 'weight': 1 },
		{ 'word': '표현하고', 'weight': 1 },
		{ 'word': '다룰', 'weight': 1 },
		{ 'word': '수', 'weight': 1 },
		{ 'word': '있도록', 'weight': 1 },
		{ 'word': '설계된', 'weight': 1 },
		{ 'word': '산업', 'weight': 1 },
		{ 'word': '표준이다', 'weight': 1 },
		{ 'word': '협회', 'weight': 1 },
		{ 'word': '가', 'weight': 1 },
		{ 'word': '제정한다', 'weight': 1 },
		{ 'word': '이', 'weight': 1 },
		{ 'word': '표준에는', 'weight': 1 },
		{ 'word': '집합', 'weight': 1 },
		{ 'word': '정보', 'weight': 1 },
		{ 'word': '데이터베이스', 'weight': 1 },
		{ 'word': '문자들을', 'weight': 1 },
		{ 'word': '다루기', 'weight': 1 },
		{ 'word': '알고리즘', 'weight': 1 },
		{ 'word': '등을', 'weight': 1 },
		{ 'word': '포함하고', 'weight': 1 },
		{ 'word': '목적은', 'weight': 1 },
		{ 'word': '현존하는', 'weight': 1 },
		{ 'word': '방법들을', 'weight': 1 },
		{ 'word': '모두', 'weight': 1 },
		{ 'word': '유니코드로', 'weight': 1 },
		{ 'word': '교체하려는', 'weight': 1 },
		{ 'word': '것이다', 'weight': 1 },
		{ 'word': '기존의', 'weight': 1 },
		{ 'word': '인코딩들은', 'weight': 1 },
		{ 'word': '그', 'weight': 1 },
		{ 'word': '규모나', 'weight': 1 },
		{ 'word': '범위', 'weight': 1 },
		{ 'word': '면에서', 'weight': 1 },
		{ 'word': '한정되어', 'weight': 1 },
		{ 'word': '있고', 'weight': 1 },
		{ 'word': '다국어', 'weight': 1 },
		{ 'word': '환경에서는', 'weight': 1 },
		{ 'word': '서로', 'weight': 1 },
		{ 'word': '호환되지', 'weight': 1 },
		{ 'word': '않는', 'weight': 1 },
		{ 'word': '문제점이', 'weight': 1 },
		{ 'word': '있었다', 'weight': 1 },
		{ 'word': '유니코드가', 'weight': 1 },
		{ 'word': '다양한', 'weight': 1 },
		{ 'word': '집합들을', 'weight': 1 },
		{ 'word': '통합하는', 'weight': 1 },
		{ 'word': '데', 'weight': 1 },
		{ 'word': '성공하면서', 'weight': 1 },
		{ 'word': '컴퓨터', 'weight': 1 },
		{ 'word': '소프트웨어의', 'weight': 1 },
		{ 'word': '국제화와', 'weight': 1 },
		{ 'word': '지역화에', 'weight': 1 },
		{ 'word': '널리', 'weight': 1 },
		{ 'word': '사용되게', 'weight': 1 },
		{ 'word': '되었으며', 'weight': 1 },
		{ 'word': '비교적', 'weight': 1 },
		{ 'word': '최근의', 'weight': 1 },
		{ 'word': '기술인', 'weight': 1 },
		{ 'word': '자바', 'weight': 1 },
		{ 'word': '그리고', 'weight': 1 },
		{ 'word': '최신', 'weight': 1 },
		{ 'word': '운영', 'weight': 1 },
		{ 'word': '체제', 'weight': 1 },
		{ 'word': '등에서도', 'weight': 1 },
		{ 'word': '지원하고', 'weight': 1 },
		{ 'word': '유니코드에서', 'weight': 1 },
		{ 'word': '한국어', 'weight': 1 },
		{ 'word': '발음을', 'weight': 1 },
		{ 'word': '나타날', 'weight': 1 },
		{ 'word': '때는', 'weight': 1 },
		{ 'word': '예일', 'weight': 1 },
		{ 'word': '로마자', 'weight': 1 },
		{ 'word': '표기법의', 'weight': 1 },
		{ 'word': '변형인', 'weight': 1 },
		{ 'word': '을', 'weight': 1 },
		{ 'word': '사용하고', 'weight': 1 },
		{ 'word': '기원은', 'weight': 1 },
		{ 'word': '년으로', 'weight': 1 },
		{ 'word': '거슬러', 'weight': 1 },
		{ 'word': '올라가며', 'weight': 1 },
		{ 'word': '이때', 'weight': 1 },
		{ 'word': '제록스의', 'weight': 1 },
		{ 'word': '베커와', 'weight': 1 },
		{ 'word': '애플의', 'weight': 1 },
		{ 'word': '리', 'weight': 1 },
		{ 'word': '콜린스', 'weight': 1 },
		{ 'word': '마크', 'weight': 1 },
		{ 'word': '데이비스가', 'weight': 1 },
		{ 'word': '통일된', 'weight': 1 },
		{ 'word': '집합을', 'weight': 1 },
		{ 'word': '만드는', 'weight': 1 },
		{ 'word': '것을', 'weight': 1 },
		{ 'word': '탐구하기', 'weight': 1 },
		{ 'word': '시작하였다', 'weight': 1 },
		{ 'word': '년', 'weight': 1 },
		{ 'word': '베커는', 'weight': 1 },
		{ 'word': '유니코드라는', 'weight': 1 },
		{ 'word': '이름의', 'weight': 1 },
		{ 'word': '다언어', 'weight': 1 },
		{ 'word': '시스템', 'weight': 1 },
		{ 'word': '를', 'weight': 1 },
		{ 'word': '초안을', 'weight': 1 },
		{ 'word': '출판하였다', 'weight': 1 },
		{ 'word': '가지', 'weight': 1 },
		{ 'word': '매핑', 'weight': 1 },
		{ 'word': '방식이', 'weight': 1 },
		{ 'word': '변환', 'weight': 1 },
		{ 'word': '형식', 'weight': 1 },
		{ 'word': '세트', 'weight': 1 },
		{ 'word': '인코딩은', 'weight': 1 },
		{ 'word': '다음을', 'weight': 1 },
		{ 'word': '포함한다', 'weight': 1 },
	],
}

export default config
