import { parse } from '@std/jsonc'
import { basename, fromFileUrl, join, relative } from '@std/path'

const inDir = './src/locales'
const outPath = './locales'
const denoDotJsoncPath = './deno.jsonc'
const localesTsPath = './src/locales.ts'

const exportLocales = (await Array.fromAsync(Deno.readDir(inDir)))
	.filter((x) => x.isFile)
	.map((x) => x.name)
	.sort((a, b) => a.localeCompare(b))

const exportsObj = Object.fromEntries(
	exportLocales.map((k) => ['./' + join(outPath, k.split('.')[0]!), './' + join(inDir, k)]),
)

const denoDotJsonc = parse(await Deno.readTextFile(denoDotJsoncPath)) as {
	exports: Record<string, string>
}

denoDotJsonc.exports = Object.fromEntries(
	Object.entries({
		...denoDotJsonc.exports,
		...exportsObj,
	}).sort(([a], [b]) => a.localeCompare(b, 'und')),
)

const locales: string[] = []

const exportMap = Object.entries(exportsObj)
	.map(([k, v]) => {
		const locale = basename(k)
		locales.push(locale)
		return `${JSON.stringify(locale)}: () => import(${
			JSON.stringify(v.replace('./src/', './'))
		}, { with: { type: 'json' } }),`
	})
	.join('\n')

await Deno.writeTextFile(denoDotJsoncPath, JSON.stringify(denoDotJsonc, null, '\t') + '\n')

const localesTs = `
// File generated by ${relative('', fromFileUrl(import.meta.url))} - do not edit directly
import { LoremBabel, type LoremBabelConfig } from './lorem.ts'

/** All available locales */
// deno-fmt-ignore
export type Locale = ${locales.map((x) => JSON.stringify(x).replaceAll(/"/g, "'")).join(' | ')}

const configs: Record<Locale, () => Promise<{ default: LoremBabelConfig}>> = {${exportMap}}

/** A map of locale codes to functions that lazily import a \`LoremBabel\` instance for that locale. */
export const locales = Object.fromEntries(
	Object.entries(configs).map(([k, v]) => {
		const getLorem = async () => new LoremBabel((await v()).default)
		return [k, getLorem]
	}),
) as Record<Locale, () => Promise<LoremBabel>>
`.trimStart()

await Deno.writeTextFile(localesTsPath, localesTs)

await new Deno.Command('deno', {
	args: ['fmt', localesTsPath],
}).spawn().output()
